import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/features/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/providers/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-container": "#2563eb",
        "inverse-surface": "#213145",
        "surface-variant": "#d3e4fe",
        "on-tertiary-container": "#bdffdb",
        "surface-tint": "#0053db",
        "on-tertiary-fixed": "#002113",
        "primary-fixed": "#dbe1ff",
        "surface-container-high": "#dce9ff",
        "tertiary-fixed": "#6ffbbe",
        "surface-container-highest": "#d3e4fe",
        background: "#f8f9ff",
        "on-primary-container": "#eeefff",
        "surface-container": "#e5eeff",
        "primary-fixed-dim": "#b4c5ff",
        "on-secondary-fixed-variant": "#3f465c",
        "on-secondary-fixed": "#131b2e",
        tertiary: "#006242",
        "on-primary": "#ffffff",
        "tertiary-container": "#007d55",
        "on-secondary-container": "#5c647a",
        "on-error": "#ffffff",
        "on-background": "#0b1c30",
        "on-surface": "#0b1c30",
        "inverse-on-surface": "#eaf1ff",
        "on-primary-fixed": "#00174b",
        error: "#ba1a1a",
        "surface-dim": "#cbdbf5",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#c3c6d7",
        "on-surface-variant": "#434655",
        outline: "#737686",
        secondary: "#565e74",
        "on-error-container": "#93000a",
        "secondary-fixed": "#dae2fd",
        "surface-container-low": "#eff4ff",
        "inverse-primary": "#b4c5ff",
        primary: "#004ac6",
        "on-tertiary": "#ffffff",
        "secondary-container": "#dae2fd",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#003ea8",
        "secondary-fixed-dim": "#bec6e0",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#4edea3",
        "on-tertiary-fixed-variant": "#005236",
        surface: "#f8f9ff",
        "surface-bright": "#f8f9ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.125rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-2xs": "0.125rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "space-lg": "1rem",
        "space-xl": "1.5rem",
        "space-2xl": "2rem",
        gutter: "1rem",
        "gutter-lg": "1.5rem",
        margin: "1rem",
        "margin-md": "1.5rem",
        "margin-lg": "2rem",
      },
      fontFamily: {
        body: ["Inter", "sans-serif"],
        headline: ["Inter", "sans-serif"],
        code: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "code-sm": ["12px", { lineHeight: "16px", letterSpacing: "0em", fontWeight: "500" }],
        "body-sm": ["13px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.025em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "500" }],
        "headline-sm": ["16px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-xl": ["32px", { lineHeight: "40px", letterSpacing: "-0.025em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default config;
